#index:
#    path: /
#    controller: App\Controller\DefaultController::index


redirect_login:
    path: /logowanie
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_login'
